import { Market } from '@/types';

// All markets we track - major asset classes with top representatives
export const MARKETS: Market[] = [
  // Equities - Major Indexes
  {
    id: 'sp500',
    name: 'S&P 500',
    category: 'equities',
    description: 'US Large Cap',
    color: '#6366F1',
    source: 'YAHOO',
    sourceId: '^GSPC',
  },
  {
    id: 'nasdaq',
    name: 'Nasdaq 100',
    category: 'equities',
    description: 'US Tech',
    color: '#8B5CF6',
    source: 'YAHOO',
    sourceId: '^NDX',
  },
  {
    id: 'russell',
    name: 'Russell 2000',
    category: 'equities',
    description: 'US Small Cap',
    color: '#A855F7',
    source: 'YAHOO',
    sourceId: '^RUT',
  },
  {
    id: 'intl',
    name: 'Intl Developed',
    category: 'equities',
    description: 'MSCI EAFE (EFA)',
    color: '#7C3AED',
    source: 'YAHOO',
    sourceId: 'EFA',
  },
  {
    id: 'emerging',
    name: 'Emerging Mkts',
    category: 'equities',
    description: 'MSCI Emerging (VWO)',
    color: '#C084FC',
    source: 'YAHOO',
    sourceId: 'VWO',
  },

  // Equity Sectors - Select Sector SPDRs
  {
    id: 'xlk',
    name: 'Technology',
    category: 'sectors',
    description: 'Tech Sector (XLK)',
    color: '#3B82F6',
    source: 'YAHOO',
    sourceId: 'XLK',
  },
  {
    id: 'xlf',
    name: 'Financials',
    category: 'sectors',
    description: 'Financial Sector (XLF)',
    color: '#10B981',
    source: 'YAHOO',
    sourceId: 'XLF',
  },
  {
    id: 'xlv',
    name: 'Healthcare',
    category: 'sectors',
    description: 'Healthcare Sector (XLV)',
    color: '#EC4899',
    source: 'YAHOO',
    sourceId: 'XLV',
  },
  {
    id: 'xle',
    name: 'Energy',
    category: 'sectors',
    description: 'Energy Sector (XLE)',
    color: '#F97316',
    source: 'YAHOO',
    sourceId: 'XLE',
  },
  {
    id: 'xli',
    name: 'Industrials',
    category: 'sectors',
    description: 'Industrial Sector (XLI)',
    color: '#6366F1',
    source: 'YAHOO',
    sourceId: 'XLI',
  },
  {
    id: 'xlp',
    name: 'Consumer Staples',
    category: 'sectors',
    description: 'Staples Sector (XLP)',
    color: '#14B8A6',
    source: 'YAHOO',
    sourceId: 'XLP',
  },
  {
    id: 'xly',
    name: 'Consumer Disc',
    category: 'sectors',
    description: 'Discretionary (XLY)',
    color: '#F59E0B',
    source: 'YAHOO',
    sourceId: 'XLY',
  },
  {
    id: 'xlu',
    name: 'Utilities',
    category: 'sectors',
    description: 'Utilities Sector (XLU)',
    color: '#64748B',
    source: 'YAHOO',
    sourceId: 'XLU',
  },

  // Fixed Income
  {
    id: 'treasury_10y',
    name: '7-10Y Treasury',
    category: 'bonds',
    description: 'Treasury Bond ETF (IEF)',
    color: '#06B6D4',
    source: 'YAHOO',
    sourceId: 'IEF',
  },
  {
    id: 'treasury_long',
    name: '20+ Yr Treasury',
    category: 'bonds',
    description: 'Long-Term Treasuries (TLT)',
    color: '#0891B2',
    source: 'YAHOO',
    sourceId: 'TLT',
  },
  {
    id: 'corp_ig',
    name: 'Corp IG Bonds',
    category: 'bonds',
    description: 'Investment Grade (LQD)',
    color: '#0EA5E9',
    source: 'YAHOO',
    sourceId: 'LQD',
  },
  {
    id: 'corp_hy',
    name: 'High Yield',
    category: 'bonds',
    description: 'Junk Bonds (HYG)',
    color: '#38BDF8',
    source: 'YAHOO',
    sourceId: 'HYG',
  },
  {
    id: 'tips',
    name: 'TIPS',
    category: 'bonds',
    description: 'Inflation Protected (TIP)',
    color: '#67E8F9',
    source: 'YAHOO',
    sourceId: 'TIP',
  },

  // Commodities - Keep major ones, add broad ETF
  {
    id: 'gold',
    name: 'Gold',
    category: 'commodities',
    description: 'Gold (GLD)',
    color: '#F59E0B',
    source: 'YAHOO',
    sourceId: 'GLD',
  },
  {
    id: 'silver',
    name: 'Silver',
    category: 'commodities',
    description: 'Silver (SLV)',
    color: '#94A3B8',
    source: 'YAHOO',
    sourceId: 'SLV',
  },
  {
    id: 'oil',
    name: 'Crude Oil',
    category: 'commodities',
    description: 'Oil Fund (USO)',
    color: '#78716C',
    source: 'YAHOO',
    sourceId: 'USO',
  },
  {
    id: 'dba',
    name: 'Agriculture',
    category: 'commodities',
    description: 'Agriculture (DBA)',
    color: '#65A30D',
    source: 'YAHOO',
    sourceId: 'DBA',
  },
  {
    id: 'dbc',
    name: 'Commodities',
    category: 'commodities',
    description: 'Broad Commodities (DBC)',
    color: '#B45309',
    source: 'YAHOO',
    sourceId: 'DBC',
  },

  // Real Estate
  {
    id: 'vnq',
    name: 'US REITs',
    category: 'real-estate',
    description: 'Vanguard REIT (VNQ)',
    color: '#EC4899',
    source: 'YAHOO',
    sourceId: 'VNQ',
  },
  {
    id: 'vnqi',
    name: 'Intl REITs',
    category: 'real-estate',
    description: 'Intl Real Estate (VNQI)',
    color: '#DB2777',
    source: 'YAHOO',
    sourceId: 'VNQI',
  },
  {
    id: 'itb',
    name: 'Home Builders',
    category: 'real-estate',
    description: 'Home Construction (ITB)',
    color: '#F472B6',
    source: 'YAHOO',
    sourceId: 'ITB',
  },

  // Currencies - Keep DXY, add currency ETFs
  {
    id: 'dxy',
    name: 'US Dollar',
    category: 'forex',
    description: 'Dollar Index (UUP)',
    color: '#22C55E',
    source: 'YAHOO',
    sourceId: 'UUP',
  },
  {
    id: 'fxe',
    name: 'Euro',
    category: 'forex',
    description: 'Euro Trust (FXE)',
    color: '#3B82F6',
    source: 'YAHOO',
    sourceId: 'FXE',
  },
  {
    id: 'fxy',
    name: 'Yen',
    category: 'forex',
    description: 'Yen Trust (FXY)',
    color: '#EF4444',
    source: 'YAHOO',
    sourceId: 'FXY',
  },

  // Crypto - Major coins
  {
    id: 'btc',
    name: 'Bitcoin',
    category: 'crypto',
    description: 'BTC/USD',
    color: '#F7931A',
    source: 'YAHOO',
    sourceId: 'BTC-USD',
  },
  {
    id: 'eth',
    name: 'Ethereum',
    category: 'crypto',
    description: 'ETH/USD',
    color: '#627EEA',
    source: 'YAHOO',
    sourceId: 'ETH-USD',
  },
  {
    id: 'sol',
    name: 'Solana',
    category: 'crypto',
    description: 'SOL/USD',
    color: '#9945FF',
    source: 'YAHOO',
    sourceId: 'SOL-USD',
  },
];

// Get markets by source for batching API calls
export const getMarketsBySource = (source: Market['source']) =>
  MARKETS.filter(m => m.source === source);

// Category metadata for display - ordered for visual grouping
export const CATEGORIES: Record<string, { label: string; color: string; order: number }> = {
  equities: { label: 'Equities', color: '#6366F1', order: 1 },
  sectors: { label: 'Sectors', color: '#3B82F6', order: 2 },
  bonds: { label: 'Fixed Income', color: '#06B6D4', order: 3 },
  commodities: { label: 'Commodities', color: '#F59E0B', order: 4 },
  'real-estate': { label: 'Real Estate', color: '#EC4899', order: 5 },
  forex: { label: 'Currencies', color: '#22C55E', order: 6 },
  crypto: { label: 'Crypto', color: '#F7931A', order: 7 },
};

// Get sorted category entries
export const getSortedCategories = () =>
  Object.entries(CATEGORIES).sort((a, b) => a[1].order - b[1].order);
